apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels: { app: logoutput }
  template:
    metadata:
      labels: { app: logoutput }
    spec:
      containers:
        - name: logoutput
          image: vanhanenjla/logoutput:1.3
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 5
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: logoutput
spec:
  selector: { app: logoutput }
  ports:
    - name: http
      port: 80
      targetPort: http
