apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  replicas: 1
  selector:
    matchLabels: { app: todoapp }
  template:
    metadata:
      labels: { app: todoapp }
    spec:
      containers:
        - name: todoapp
          image: vanhanenjla/todoapp:1.2
          env:
            - name: PORT
              value: "8181"
          ports:
            - name: http
              containerPort: 8181
          livenessProbe:
            httpGet: { path: /health, port: 8181 }
            initialDelaySeconds: 5
          readinessProbe:
            httpGet: { path: /health, port: 8181 }
            initialDelaySeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp
spec:
  selector: { app: todoapp }
  ports:
    - name: http
      port: 80
      targetPort: http
